//
// Created by Tammy S on 10/19/23.
//

#ifndef SFML_TEMPLATE_FONTENUM_H
#define SFML_TEMPLATE_FONTENUM_H

enum fontEnum {
    LATO, NOTO_SANS, OPEN_SANS, PRODUCT_SANS, COURIER, EMOJI
};

#endif //SFML_TEMPLATE_FONTENUM_H
